### PR TITLE
Fix build issues

### PR DESCRIPTION
**Pull request by Declan-Reid**

### CODE REVIEW

**Comment by aoiyu-dev** [comment]
You will lose support for ARM devices like M Series chips and such. This alpha build of NFDSharp should not be causing build issues, your issue is elsewhere.

**Comment by Declan-Reid** [comment]
No I don't believe this was the issue at all, this one had nothing to do with it. I just wasn't sure why it was using alpha.

**Comment by Declan-Reid** [comment]
ARM should build fine now.

**Comment by aoiyu-dev** [comment]
> ARM should build fine now.

Don’t forget to update the automation to use 0.6.0 alpha in the install. It will not auto to it unless it is latest, 0.6.0 alpha of course is a prerelease.

**Comment by Declan-Reid** [comment]
I don't think I ever removed it from the automation.

**Comment by Declan-Reid** [comment]
I'm pretty sure anything that I've kept here has been solved so imma close this

**Pull request closed without merging**
